// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "eu-central-1",
    "aws_cognito_identity_pool_id": "eu-central-1:74a839ae-a88b-476c-84e9-64d9be07456f",
    "aws_cognito_region": "eu-central-1",
    "aws_user_pools_id": "eu-central-1_eWFYK47jQ",
    "aws_user_pools_web_client_id": "1ac0eoemhf2l8bjc7bcpje48q2",
    "aws_appsync_graphqlEndpoint": "https://35k5w3j4u5fyzpkkd4kqawnrby.appsync-api.eu-central-1.amazonaws.com/graphql",
    "aws_appsync_region": "eu-central-1",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS",
    "aws_content_delivery_bucket": "wavepage-static-files-dev",
    "aws_content_delivery_bucket_region": "eu-central-1",
    "aws_content_delivery_url": "https://d1zvu8f5vu3lhe.cloudfront.net"
};


export default awsmobile;
