// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
  aws_project_region: "eu-central-1",
  aws_cognito_identity_pool_id:
    "eu-central-1:03a7b08a-48bd-43e0-9b4b-7b7304626e14",
  aws_cognito_region: "eu-central-1",
  aws_user_pools_id: "eu-central-1_wWrsz44gZ",
  aws_user_pools_web_client_id: "67t8d89lqfhriv9u2oibjti3um",
  oauth: {},
  aws_appsync_graphqlEndpoint:
    "https://vazrt4nz7jgexlknv5jtmgvxdm.appsync-api.eu-central-1.amazonaws.com/graphql",
  aws_appsync_region: "eu-central-1",
  aws_appsync_authenticationType: "AMAZON_COGNITO_USER_POOLS",
  aws_content_delivery_bucket: "withspeech-20191006171248-hostingbucket-dev",
  aws_content_delivery_bucket_region: "eu-central-1",
  aws_content_delivery_url: "https://dk9h0jllfap67.cloudfront.net"
};

export default awsmobile;
